#!/bin/sh

# Return ip of droplet based on it's name 
filter='.droplets[] | select(.name=="'"$DROPLET_NAME"'") | .networks.v4[0].ip_address'
curl -X GET "https://api.digitalocean.com/v2/droplets" -H "Authorization: Bearer $TOKEN" | jq "$filter" --raw-output

# --raw-output removes the quotes. 
# Example: "104.236.176.181" -> 104.236.176.181
